# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres-image
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gabriel
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: app-image
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gabriel
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
