# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gabriel
    ports:
      - "5432:5432"
  app:
    image: testing
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/food
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gabriel
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
